services:
  backend:
    image: 'project-estimation:latest'
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/backend-0.0.1-SNAPSHOT.jar
    container_name: project-estimation
    ports:
      - "8080:8080" # host:container
    env_file:
      - backend/src/main/resources/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/project-estimate
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - ./backend/src/main/resources/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck: # Ensure database is fully initialized before starting backend
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge