services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./backend/src/main/resources/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: