server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ProjectEstimation
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        default_batch_fetch_size: ${SPRING_JPA_FETCH_SIZE} # To batch list queries
        format_sql: ${SPRING_JPA_FORMAT_SQL}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_JPA_SHOW_SQL}

security:
  jwt:
    secret: ${JWT_SECRET_KEY}
    token-expiration: ${JWT_TOKEN_EXPIRATION}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              DdlType: debug