server:
  port: ${SERVER_PORT}

spring:
  sql:
    init:
      mode: always # This makes spring run the resources/data.sql after DB schema init.
  application:
    name: ProjectEstimation
  profiles:
    active: ${ACTIVE_PROFILES}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        default_batch_fetch_size: ${SPRING_JPA_FETCH_SIZE} # To batch list queries
        format_sql: ${SPRING_JPA_FORMAT_SQL}
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SPRING_JPA_SHOW_SQL}

springdoc:
  api-docs:
    path: /api-docs

security:
  jwt:
    secret: ${JWT_SECRET_KEY}
    token-expiration: ${JWT_TOKEN_EXPIRATION}

logging:
  level:
    io:
      fervo:
        takecost:
          projectestimation: DEBUG
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              DdlType: debug