name: Backend CI/CD

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'backend/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Fix permission issue with gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }} # Do not upload artifacts when running locally using Act command-line
        with:
          name: app-jar
          path: backend/build/libs/*.jar

      - name: Save build outputs locally when using Act command-line
        if: ${{ env.ACT }}
        run: |
          mkdir -p local-artifacts/backend
          cp backend/build/libs/*.jar local-artifacts/backend
          echo "📁 Build outputs saved to: $(realpath local-artifacts/backend)"

  docker-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - name: Download backend JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: backend/

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Build backend Docker image
        run: docker build -t ghcr.io/fervo-inc/project-estimation:latest -f backend/Dockerfile --build-arg JAR_FILE=backend-0.0.1-SNAPSHOT.jar backend/

      - name: Push backend Docker image
        run: docker push ghcr.io/fervo-inc/project-estimation:latest

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0